---
exclude_paths:
- bin/**
- build/**
- node_modules/**
- vendor/**
- tests/**
engines:
  phpcodesniffer:
    enabled: true
  eslint:
    enabled: true
ratings:
   paths:
   - assets/**
   - includes/**